use_frameworks!

platform :ios, '9.0'

target 'FlaneurOpen_Example' do
  pod 'FlaneurOpen', :path => '../'

  # Google Places API
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'GoogleMaps'

  target 'FlaneurOpen_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.1.0'
    pod 'Nimble', '~> 7.0.0'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end
